# Generated by Django 2.2.7 on 2019-11-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peertotur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ftype',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
